#!/usr/bin/env python3
"""Validate the data/ contract the dashboard depends on.

`index.html` fetches a fixed set of `data/*.json` files and reads specific
keys out of each. If a refresh script blanks a file, drops a required key, or
writes malformed JSON, the dashboard silently breaks in the browser — there is
no server to catch it. This script encodes those contracts so a bad refresh is
caught in CI (and locally) *before* it reaches master and redeploys.

Design notes:
  * Pure standard library — no third-party deps, runs anywhere Python 3.9+ does.
  * Forward-compatible: extra keys are always fine. We only fail on a MISSING
    required key, the wrong container type, or malformed JSON — the things that
    actually break the dashboard. Cosmetic drift is never a failure.
  * Structural problems are errors (exit 1). "Looks empty" is a warning only,
    because a genuinely flat book / quiet news day is legitimate.

Usage:
    python scripts/validate_data.py            # validate ./data
    python scripts/validate_data.py --data DIR # validate a specific dir

Exit code 0 = all contracts hold, 1 = at least one error.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

# ── Contract specs ────────────────────────────────────────────────────────────
# For each file the dashboard consumes:
#   container : dict | list  — the top-level JSON type
#   required  : keys that must be present on a dict (ignored for lists)
#   rows      : (field_holding_the_list, [required keys on each row]) — optional
# Extra keys beyond these are always allowed.
DICT, LIST = dict, list

SPECS: dict[str, dict] = {
    # Portfolio — the load-bearing files. A break here empties the KPI cards.
    "positions.json": {
        "container": DICT,
        "required": ["updatedAt", "positions"],
        "rows": ("positions", ["ticker", "side", "shares", "mktValue"]),
        "want_rows": True,  # an empty book is suspicious enough to warn on
    },
    "account.json": {
        "container": DICT,
        "required": [
            "updatedAt", "nav", "cash", "dailyPnl",
            "longExposure", "shortExposure", "netExposure", "grossExposurePct",
        ],
    },
    "pnl.json": {
        "container": LIST,
        "rows": (None, ["timestamp", "nav"]),
        "want_rows": True,
    },
    "benchmarks.json": {
        "container": DICT,
        "required": ["updatedAt", "tickers"],
        "benchmarks": True,  # special: each ticker → equal-length dates/closes
    },
    # Static strategy report — regenerated by hand, not by a refresh script.
    # We guard its headline keys so an accidental overwrite can't blank the tab.
    "report.json": {
        "container": DICT,
        "required": ["asOf", "title", "headline"],
    },
    # Stock Picks compiler output.
    "micro.json": {
        "container": DICT,
        "required": ["updatedAt", "tickers", "recommendations"],
        "rows": ("tickers", ["ticker"]),
        "want_rows": True,
    },
    # The uniform {updatedAt, items:[...]} family the secondary tabs read.
    "analysts.json":    {"container": DICT, "required": ["updatedAt", "items"],
                         "rows": ("items", ["ticker"])},
    "news.json":        {"container": DICT, "required": ["updatedAt", "items"],
                         "rows": ("items", ["title"])},
    "commodities.json": {"container": DICT, "required": ["updatedAt", "items"],
                         "rows": ("items", ["name"])},
    "technicals.json":  {"container": DICT, "required": ["updatedAt", "items"],
                         "rows": ("items", ["ticker"])},
    "macro.json":       {"container": DICT, "required": ["updatedAt", "items"],
                         "rows": ("items", ["label"])},
    "research.json":    {"container": DICT, "required": ["updatedAt", "items"],
                         "rows": ("items", ["ticker"])},
    "metals_spot.json": {"container": DICT, "required": ["updatedAt", "items"],
                         "rows": ("items", ["name"])},
    # Process tab (see PROCESS.md). Line-delimited files (decision_log.jsonl,
    # orders.jsonl — the latter feeds the Orders tab) can't live in SPECS
    # (validate_file whole-file-parses); they get a per-line parse in step 3
    # of main() plus warn-only semantic checks in verify_data.check_process_files().
    "channel_accuracy.json": {"container": DICT, "required": ["updatedAt", "gate", "channels"],
                              "rows": ("channels", ["id", "kind", "status"])},
    "alerts.json":      {"container": DICT, "required": ["updatedAt", "items"],
                         "rows": ("items", ["type", "severity", "message"])},
}


def _type_name(t: type) -> str:
    return {dict: "object", list: "array"}.get(t, t.__name__)


def validate_file(path: pathlib.Path, spec: dict, errors: list, warnings: list) -> None:
    rel = f"data/{path.name}"
    try:
        doc = json.loads(path.read_text())
    except FileNotFoundError:
        errors.append(f"{rel}: missing (dashboard fetches this file)")
        return
    except json.JSONDecodeError as e:
        errors.append(f"{rel}: invalid JSON — {e}")
        return

    container = spec["container"]
    if not isinstance(doc, container):
        errors.append(f"{rel}: expected top-level {_type_name(container)}, "
                      f"got {_type_name(type(doc))}")
        return

    # Required top-level keys (dicts only).
    for key in spec.get("required", []):
        if key not in doc:
            errors.append(f"{rel}: missing required key '{key}'")

    # Row-level checks (list at `field`, or the doc itself when field is None).
    rows_spec = spec.get("rows")
    if rows_spec:
        field, row_keys = rows_spec
        rows = doc if field is None else doc.get(field)
        if rows is None:
            pass  # already reported by the required-key check above
        elif not isinstance(rows, list):
            where = "top level" if field is None else f"'{field}'"
            errors.append(f"{rel}: {where} must be an array of rows")
        else:
            if not rows and spec.get("want_rows"):
                warnings.append(f"{rel}: no rows — verify the refresh actually ran")
            # Check the first few rows; a schema break shows up on row 0.
            for i, row in enumerate(rows[:5]):
                if not isinstance(row, dict):
                    errors.append(f"{rel}: row {i} is not an object")
                    continue
                for rk in row_keys:
                    if rk not in row:
                        errors.append(f"{rel}: row {i} missing key '{rk}'")

    # Benchmarks: each ticker maps to equal-length dates/closes arrays.
    if spec.get("benchmarks"):
        tickers = doc.get("tickers")
        if not isinstance(tickers, dict):
            errors.append(f"{rel}: 'tickers' must be an object")
        else:
            for tkr, series in tickers.items():
                if not isinstance(series, dict):
                    errors.append(f"{rel}: {tkr} must be an object")
                    continue
                dates, closes = series.get("dates"), series.get("closes")
                if not isinstance(dates, list) or not isinstance(closes, list):
                    errors.append(f"{rel}: {tkr} needs 'dates' and 'closes' arrays")
                elif len(dates) != len(closes):
                    errors.append(f"{rel}: {tkr} dates/closes length mismatch "
                                  f"({len(dates)} vs {len(closes)})")


def main() -> int:
    ap = argparse.ArgumentParser(description="Validate the dashboard data contract.")
    ap.add_argument("--data", default=None,
                    help="data directory (default: <repo>/data)")
    args = ap.parse_args()

    data_dir = (pathlib.Path(args.data) if args.data
                else pathlib.Path(__file__).resolve().parent.parent / "data")
    if not data_dir.is_dir():
        print(f"error: data directory not found: {data_dir}", file=sys.stderr)
        return 1

    errors: list[str] = []
    warnings: list[str] = []

    # 1) Every file with a declared contract must satisfy it.
    for name, spec in SPECS.items():
        validate_file(data_dir / name, spec, errors, warnings)

    # 2) Every *other* committed data/*.json must at least parse — a corrupt
    #    file anywhere in data/ is a problem even if the dashboard doesn't read it.
    known = set(SPECS)
    for path in sorted(data_dir.glob("*.json")):
        if path.name in known:
            continue
        try:
            json.loads(path.read_text())
        except json.JSONDecodeError as e:
            errors.append(f"data/{path.name}: invalid JSON — {e}")

    # 3) Line-delimited data/*.jsonl (orders log, history files): every
    #    non-blank line must parse — the dashboard's Orders tab collapses the
    #    whole log to empty on a single bad line. An absent or empty file is
    #    fine (logs legitimately start empty): blanked-is-legal,
    #    malformed-is-fatal, same as above.
    for path in sorted(data_dir.glob("*.jsonl")):
        for i, line in enumerate(path.read_text().splitlines(), 1):
            if not line.strip():
                continue
            try:
                json.loads(line)
            except json.JSONDecodeError as e:
                errors.append(f"data/{path.name}: line {i} invalid JSON — {e}")

    for w in warnings:
        print(f"  war: {w}")
    for e in errors:
        print(f"  ERR: {e}")

    checked = len(SPECS)
    if errors:
        print(f"\n✗ data contract FAILED — {len(errors)} error(s) across "
              f"{checked} contracted files.")
        return 1
    print(f"✓ data contract OK — {checked} contracted files"
          + (f", {len(warnings)} warning(s)" if warnings else "") + ".")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
